

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: cognispeech-backend
    ports:
      - "8000:8000"
    volumes:
      - backend-data:/app/data
      - backend-uploads:/app/uploads
      - backend-logs:/app/logs
      - backend-cache:/app/cache
      - backend-models:/app/model_cache
    environment:
      - DATABASE_URL=sqlite:///./data/cognispeech.db
      - MAX_FILE_SIZE=52428800
      - WHISPER_MODEL=base.en
      - SENTIMENT_MODEL=siebert/sentiment-roberta-large-english
      - DEBUG=false
    restart: unless-stopped
    networks:
      - cognispeech-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/analysis/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./Second_Frontend
      dockerfile: Dockerfile
    container_name: cognispeech-frontend
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - cognispeech-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  backend-data:
  backend-uploads:
  backend-logs:
  backend-cache:
  backend-models:

networks:
  cognispeech-network:
    driver: bridge
