# A string used to distinguish different Supabase projects on the same host. Defaults to the
# working directory name when running `supabase init`.
project_id = "cognispeech"

[api]
enabled = true
# Port to use for the API URL.
port = 54321
# Schemas to expose in your API. Tables, views and stored procedures in this schema will get API endpoints.
# public and storage are always included.
schemas = ["public", "storage", "graphql_public"]
# Extra schemas to add to the search_path of every request. public is always included.
extra_search_path = ["public", "extensions"]
# The maximum number of rows returned from a table or view. Limits payload size for accidental or malicious requests.
max_rows = 1000

[db]
# Port to use for the local database URL.
port = 54322
# Port used by db diff command to initialize a shadow database. This port must be different from the main database port.
shadow_port = 54320
# The database major version to use. This has to be the same as your remote database's. Run `SHOW server_version;` on the remote database to check.
major_version = 15

[db.pooler]
enabled = false
# Port to use for the local connection pooler.
port = 54329
# Specifies when a server connection can be reused by other clients.
# https://www.postgresql.org/docs/current/runtime-config-connection.html#RUNTIME-CONFIG-CONNECTION-POOLING
pool_mode = "transaction"
# How many server connections to allow per user/database pair.
# https://www.postgresql.org/docs/current/runtime-config-connection.html#RUNTIME-CONFIG-CONNECTION-POOLING
default_pool_size = 15
# Maximum number of client connections allowed.
# https://www.postgresql.org/docs/current/runtime-config-connection.html#RUNTIME-CONFIG-CONNECTION-POOLING
max_client_conn = 100

[realtime]
enabled = true
# Bind realtime via either IPv4 or IPv6. (default: IPv4)
# ip_version = "IPv4"

[studio]
enabled = true
# Port to use for Supabase Studio.
port = 54323
# External URL of the API server that frontend connects to.
api_url = "http://localhost:54321"

# Email testing server. Emails sent with the local dev setup are not actually sent - rather, they
# are monitored, and you can view the emails that would have been sent from the web interface.
[inbucket]
enabled = true
# Port to use for the email testing server web interface.
port = 54324
# Uncomment to expose additional ports for testing user applications that send emails.
# smtp_port = 2500
# pop3_port = 1100

[storage]
enabled = true
# The maximum file size allowed (e.g. "5MB", "500KB").
file_size_limit = "50MiB"

[auth]
enabled = true
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://localhost:3000"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["https://localhost:3000"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604800 (one week).
jwt_expiry = 3600
# If disabled, the refresh token will never expire.
enable_refresh_token_rotation = true
# Allows refresh tokens to be reused after expiry, up to the specified interval in seconds.
# Requires enable_refresh_token_rotation = true.
refresh_token_reuse_interval = 10
# Allow/disallow new user signups to your project.
enable_signup = true

[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old, and new email addresses. If disabled, only the new email is required to confirm.
double_confirm_changes = true
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = false

# Uncomment to customize email template
# [auth.email.template.invite]
# subject = "You have been invited"
# content_path = "./supabase/templates/invite.html"

# Uncomment to customize email template
# [auth.email.template.confirmation]
# subject = "Confirm your signup"
# content_path = "./supabase/templates/confirmation.html"

# Uncomment to customize email template
# [auth.email.template.recovery]
# subject = "Reset your password"
# content_path = "./supabase/templates/recovery.html"

# Uncomment to customize email template
# [auth.email.template.magic_link]
# subject = "Your magic link"
# content_path = "./supabase/templates/magic_link.html"

# Uncomment to customize email template
# [auth.email.template.email_change]
# subject = "Confirm your email change"
# content_path = "./supabase/templates/email_change.html"

# Uncomment to customize email template
# [auth.email.template.reauthenticate]
# subject = "Confirm your action"
# content_path = "./supabase/templates/reauthenticate.html"

# Use pre-defined map of claims that are safe to pass to the JWT. This is the default.
# [auth.jwt]
# admin_group_name = "service_role"
# default_group_name = "authenticated"
# issuer = "supabase"
# secret = "your-super-secret-jwt-token-with-at-least-32-characters-long"
# expiry = 3600
# refresh_rotation_interval = 10

# Configure one of the supported SMS providers: `twilio`, `twilio_verify`, `messagebird`, `textlocal`, `vonage`.
# [auth.sms]
# enable_signup = true
# enable_confirmations = false
# template = "Your code is {{ .Code }}"
# max_frequency = 1m

# Use an external OAuth provider. The full list of providers are: `apple`, `azure`, `bitbucket`,
# `discord`, `facebook`, `github`, `gitlab`, `google`, `keycloak`, `linkedin`, `notion`, `twitch`,
# `twitter`, `slack`, `spotify`, `workos`, `zoom`.
# [auth.external.apple]
# enabled = true
# client_id = "your-apple-client-id"
# secret = "your-apple-client-secret"
# # Overrides the default auth redirectUrl.
# redirect_uri = "https://localhost:3000/auth/callback"
# # Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure,
# # or any other third-party OIDC providers.
# url = "https://appleid.apple.com" 